Accounting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('users/', include('users.urls')),
    path('bills/', include('bills.urls')),
    path('api/', include('api.urls'))
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getData, name='getData'),
]

bills/urls.py
from django.urls import path
from . import views

app_name = 'bills'
urlpatterns = [
    path('', views.index, name='index'), #, namespace='bills'
    path('add', views.add, name='add'),
    path('delete_bill', views.delete_bill, name='delete_bill'),
    path('<int:bill_id>', views.bill, name='bill'),
    path('<int:bill_id>/add_item', views.add_item, name='add_item'),
    path('<int:bill_id>/assign_payment', views.assign_payment, name='assign_payment'),
    path('<int:bill_id>/delete_payment', views.delete_payment, name='delete_payment'),
    path('api/get_bills', views.get_bills, name='api_get_bills'),
    path('api/get_all_users', views.get_all_users, name='get_all_users')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('pay/<str:lender_username>', views.pay, name='pay'),
    path('pay/<str:lender_username>/make_payment', views.make_payment, name='make_payment'),
    path('receive/<str:borrower_username>', views.receive, name='receive'),
    path('receive/<str:borrower_username>/receive_payment', views.receive_payment, name='receive_payment')
]

bills/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Bill(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    comment = models.CharField(max_length=500, blank=True)
    lender = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='lender', editable = True, blank=True)
    
    def _is_payed(self):
        "Returns true if it has payments and all payments are payed"
        all_items = Item.objects.filter(bill = self).all()
        Payed_payments = Item_Payment.objects.filter(item__in = all_items).filter(is_payed = True).all()
        All_payments = Item_Payment.objects.filter(item__in = all_items).all()

        if All_payments and (list(All_payments) == list(Payed_payments)):
            return True
        else:
            return False
    
    is_payed = property(_is_payed)
    
    def __str__(self):
        return f'{self.name} {self.date}' #: {self.cost_total}rub'



class Item(models.Model):
    name = models.CharField(max_length=500)
    amount = models.PositiveIntegerField()
    cost_per_exemplar = models.PositiveIntegerField()
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE, related_name='items')


    def _get_cost_total(self):
        return self.amount*self.cost_per_exemplar
    
    cost_total = property(_get_cost_total)


    def __str__(self):
        return f'{self.name}: {self.amount}x{self.cost_per_exemplar} rub'
    


class Item_Payment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='payments')
    # the one who has to pay for this Items (borrower)
    payer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='payers')
    # the part that this payer must pay for this item
    paying_part = models.FloatField(editable = True, validators=[MinValueValidator(0.0), MaxValueValidator(1.0)])
    is_payed = models.BooleanField(editable = True, default = False)

    # https://stackoverflow.com/questions/17682567/how-to-add-a-calculated-field-to-a-django-model
    def _get_paying_amount(self):
        "Returns the paing amount"
        return round(self.paying_part*self.item.cost_per_exemplar*self.item.amount, 2)
    
    paying_amount = property(_get_paying_amount)

    def _get_lender(self):
        "Returns the lender of the bill where the item is on"
        return self.item.bill.lender
    # the one who had payed (lender)
    lender = property(_get_lender)

    def __str__(self):
        return f'For {self.item.name} {self.payer} has to pay {self.paying_amount} rub'

bills/views.py
from datetime import date

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model

##### API
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import BillSerializer, ItemSerializer, Item_PaymentSerializer, UserSerializer
import json

from .models import Bill, Item, Item_Payment

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    acc_user = request.user

    All_bills = Bill.objects.all()
    
    # not payed bills [bill_str, bill_id]
    not_payed_bills = []
    for bill in All_bills:
        if not bill.is_payed:
            not_payed_bills.append([str(bill), bill.id])


    User = get_user_model()
    users = User.objects.all()
    return render(request, 'bills/index.html', {
            'user': acc_user,
            'first_name_first_letter': acc_user.first_name[0],
            'last_name_first_letter': acc_user.last_name[0],
            'not_payed_bills': not_payed_bills,
            'users': users
        })

def add(request):
    if request.method == 'POST':
        name = request.POST['name']
        date = request.POST['date']
        comment = request.POST['comment']
        lender_id = int(request.POST['lender'])
        User = get_user_model()
        lender = User.objects.get(id = lender_id)
        bill = Bill(name = name, date = date, comment=comment, lender = lender)
        bill.save()
        return HttpResponseRedirect(reverse('bills:index'))



def delete_bill(request):
    if request.method == 'POST':
        bill_id = int(request.POST['bill_id'])
        bill = Bill.objects.get(id = bill_id)
        bill.delete()

        return HttpResponseRedirect(reverse('bills:index'))



def bill(request, bill_id):
    users = get_user_model().objects.all()
    bill = Bill.objects.get(id = bill_id)
    items = Item.objects.filter(bill = bill).all().order_by('id')
    payments = Item_Payment.objects.filter(item__in = items).all().order_by('payer', 'item_id')

    # total cost is method therefore i have to iterate to count it
    total_costs = 0
    for item in items:
        total_costs += item.cost_total
    

    return render(request, 'bills/bill.html', {
            'bill': bill,
            'items': items,
            'total_costs': total_costs,
            'payments': payments,
            'users': users
        })



def add_item(request, bill_id):
    if request.method == 'POST':
        name = request.POST['name']
        amount = request.POST['amount']
        cost_per_exemplar = request.POST['cost_per_exemplar']
        bill = Bill.objects.get(id = bill_id)
        item = Item(name=name, amount=amount, cost_per_exemplar = cost_per_exemplar, bill=bill)
        item.save()
        return HttpResponseRedirect(reverse('bills:bill', args=(bill_id, )))


def assign_payment(request, bill_id):
    if request.method == 'POST':
        item_id = int(request.POST['item'])
        payer_id = int(request.POST['payer'])
        paying_part = float(request.POST['paying_part'])

        item = Item.objects.get(id = item_id)
        payer = get_user_model().objects.get(id = payer_id)

        item_payment = Item_Payment(item = item, payer = payer, paying_part = paying_part)
        item_payment.save()
        return HttpResponseRedirect(reverse('bills:bill', args=(bill_id, )))



def delete_payment(request, bill_id):
    if request.method == 'POST':
        payment_id = int(request.POST['payment'])
        Item_Payment.objects.filter(id = payment_id).delete()
        return HttpResponseRedirect(reverse('bills:bill', args=(bill_id, )))

########################### APIs ###########################
############################################################

@api_view(['GET'])
def get_bills(request):

    not_payed_bills = []
    for bill in Bill.objects.all():
        if not bill.is_payed:
            serializedBill = BillSerializer(bill).data

            lender = get_user_model().objects.get(id = serializedBill["lender"])
            serializedBill["lender"] = UserSerializer(lender).data

            items = Item.objects.filter(bill = bill).all()
            serializedBill["items"] = ItemSerializer(items, many = True).data

            #making empty user dictionary
            #{"first_name": {"amount", "is_payed"}}
            paymentsByUser = {}
            for user in get_user_model().objects.all():
                paymentsByUser[user.first_name] = {"amount": 0, "is_payed": "True"}

            for i in range(len(items)):
                item = items[i]

                # need that to not miss total sum
                itemCost = item.cost_total

                payments = Item_Payment.objects.filter(item_id = item.id).all()

                #calculating amounts
                for payment in payments:
                    payerFistName = get_user_model().objects.get(id = payment.payer.id).first_name
                    paymentsByUser[payerFistName]["amount"] += payment.paying_amount
                    itemCost -= payment.paying_amount

                    if not payment.is_payed:
                        paymentsByUser[payerFistName]["is_payed"] = "False"
                
                #adding difference to lender
                paymentsByUser[lender.first_name]["amount"] += itemCost

            #transforming user dictionary to [{"name", "amount", "is_payed"}, {}]
            paymentsByUserT = []
            for user in get_user_model().objects.all():
                obj = {"name": user.first_name}
                obj["amount"] = round(paymentsByUser[user.first_name]["amount"])
                obj["is_payed"] = paymentsByUser[user.first_name]["is_payed"]
                paymentsByUserT.append(obj)

            #adding final dictionary to bill object
            serializedBill["payments"] = paymentsByUserT

            # adding bill object to list of bills
            not_payed_bills.append(serializedBill)

    return Response(not_payed_bills)


@api_view(['GET'])
def get_all_users(request):
    return Response(UserSerializer(get_user_model().objects.all(), many=True).data)

bills/templates/bills/bill.html
{% extends 'bills/layout.html' %}

{% block body %}
<header class="subHeader">
    <nav>
        <l1 class="title">Bill: {{ bill }}</l1>
    </nav>
</header>
<div class="mainBox">
    <div class="ItemsBox">
        <l1 class="title">Items</l1>
        <div class="card" style="padding-bottom: 0%;">
            <div class="card-body">
                {% if bill.items %}
                <ul class="list">
                {% for item in items %}
                    <li>{{ item }}</li>
                {% endfor %}
                </ul>
                <div>
                    Total: {{ total_costs }}
                </div>
                {% else %}
                    <l3>Bill has no items</l3>
                {% endif %}
            </div>
        </div>
        <div class="subMainBox">
            <div class="subFormBoxLeft">
                <l1 class="title">Add Item</l1>
                <form action="{% url 'bills:add_item' bill.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Enter item name</label>
                        <input class="form-control" type="text" placeholder="name e.g. Чиабатта" name="name">
                    </div>
                    <div class="form-group">
                        <label>Enter items amount</label>
                        <input class="form-control"  type="number" placeholder="кол-во" name="amount">
                    </div>
                    <div class="form-group">
                        <label>Enter cost per item</label>
                        <input class="form-control"  type="number" placeholder="затраты на штуку" name="cost_per_exemplar">
                    </div>
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
            <div class="subFormBox">
                <l1 class="title">Assign payment</l1>
                <form action="{% url 'bills:assign_payment' bill.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Choose Item</label>
                        <select class="form-control" name="item">
                            {% for item in items %}
                                <option value="{{ item.id }}">{{ item }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Choose Payer</label>
                        <select class="form-control" name="payer">
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Enter cost share</label>
                        <input class="form-control"  type="number" step="0.01" placeholder="доля затрат" name="paying_part">
                    </div>
                    <button type="submit" class="btn btn-primary">Assign</button>
                </form>
            </div>
        </div>
    </div>


    <div class="paymentsBox">
        <l1 class="title">Payments</l1>
        <div class="card" style="padding-bottom: 0%; margin-bottom: 10px;">
            <div class="card-body">
                {% if payments %}
                    <ul class="list">
                    {% for payment in payments %}
                        <li> {{ payment.payer }}: for {{ payment.item.name }} has to pay {{ payment.paying_part }}</li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <l3>Bill has no payments</l3>
                {% endif %}
            </div>
        </div>
        <l1 class="title">Delete payment</l1>
        <form action="{% url 'bills:delete_payment' bill.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Choose Payment</label>
                <select class="form-control" name="payment">
                    {% for payment in payments %}
                        <option value="{{ payment.id }}">{{ payment.payer }}: for {{ payment.item.name }} has to pay {{ payment.paying_part }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

bills/templates/bills/billOld.html
{% extends 'bills/layout.html' %}

{% block body %}
<header class="subHeader">
    <nav>
        <l1 class="title">Bill: {{ bill }}</l1>
    </nav>
</header>
<div class="mainBox">
    <div class="ItemsBox">
        <l1 class="title">Items</l1>
        <div class="card" style="padding-bottom: 0%;">
            <div class="card-body">
                {% if bill.items %}
                <ul class="list">
                {% for item in items %}
                    <li>{{ item }}</li>
                {% endfor %}
                </ul>
                <div>
                    Total: {{ total_costs }}
                </div>
                {% else %}
                    <l3>Bill has no items</l3>
                {% endif %}
            </div>
        </div>
        <div class="subMainBox">
            <div class="subFormBoxLeft">
                <l1 class="title">Add Item</l1>
                <form action="{% url 'bills:add_item' bill.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Enter item name</label>
                        <input class="form-control" type="text" placeholder="name e.g. Чиабатта" name="name">
                    </div>
                    <div class="form-group">
                        <label>Enter items amount</label>
                        <input class="form-control"  type="number" placeholder="кол-во" name="amount">
                    </div>
                    <div class="form-group">
                        <label>Enter cost per item</label>
                        <input class="form-control"  type="number" placeholder="затраты на штуку" name="cost_per_exemplar">
                    </div>
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
            <div class="subFormBox">
                <l1 class="title">Assign payment</l1>
                <form action="{% url 'bills:assign_payment' bill.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Choose Item</label>
                        <select class="form-control" name="item">
                            {% for item in items %}
                                <option value="{{ item.id }}">{{ item }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Choose Payer</label>
                        <select class="form-control" name="payer">
                            {% for user in users %}
                                <option value="{{ user.id }}">{{ user }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Enter cost share</label>
                        <input class="form-control"  type="number" step="0.01" placeholder="доля затрат" name="paying_part">
                    </div>
                    <button type="submit" class="btn btn-primary">Assign</button>
                </form>
            </div>
        </div>
    </div>


    <div class="paymentsBox">
        <l1 class="title">Payments</l1>
        <div class="card" style="padding-bottom: 0%; margin-bottom: 10px;">
            <div class="card-body">
                {% if payments %}
                    <ul class="list">
                    {% for payment in payments %}
                        <li> {{ payment.payer }}: for {{ payment.item.name }} has to pay {{ payment.paying_part }}</li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <l3>Bill has no payments</l3>
                {% endif %}
            </div>
        </div>
        <l1 class="title">Delete payment</l1>
        <form action="{% url 'bills:delete_payment' bill.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Choose Payment</label>
                <select class="form-control" name="payment">
                    {% for payment in payments %}
                        <option value="{{ payment.id }}">{{ payment.payer }}: for {{ payment.item.name }} has to pay {{ payment.paying_part }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

bills/templates/bills/index.html
{% extends 'bills/layout.html' %}

{% block body %}
<div class="main">
    <div class="bills-list-box">
        <div class="bills-list-head">
            <h3 class="bold" id="bills-are-payed-by">Bills are payed by</h3>
            <i class="arrow down"></i>
        </div>
        <div class="bills-list-users-list" style="display:none;">
            <div class="bills-list-users-list-item-current">
                <div class="checkmark"></div>
                <h5>All</h5>
            </div>
        </div>
        <div class="bills-list">
        </div>
        <div class="bills-list-show-more">
            <h5 class="bold" id="show-more">Show more</h5>
            <h5 class="bold" id="show-less" style="display:none;">Show less</h5>
        </div>
    </div>
    
    <div class="bill">
        <h2 class="bill-header"></h2>
        <div class="bill-payment-box">
            <div class="bill-payment-box-item" style="display:none;">
                <h4 class="bill-payment-box-item-name"></h4>
                <h4 class="bill-payment-box-item-cost"></h4>
                <h4 class="bill-payment-box-item-items"></h4>
            </div>
        </div>
        <div class="bill-share-box">
            <div class="bill-share-box-item" style="display:none;">
                <h4 class="bill-share-box-item-name"></h4>
                <h4 class="bill-share-box-item-amount"></h4>
                <div class="bill-share-box-item-is-payed"></div>
            </div>
        </div>
        <div class="bill-share-box-item-total" style="display:none;">
            <h4 class="bill-share-box-item-name bold">Total</h4>
            <h4 class="bill-share-box-item-amount bold"></h4>
        </div>
    </div>
</div>
{% endblock %}

bills/templates/bills/indexOld.html
{% extends 'bills/layout.html' %}

{% block body %}
<div class="mainBox">
    <div class="listBox">
        <l1 class="title">All bills</l1>
        <div class="card">
            <div class="card-body">
                <ul class="list">
                    {% for bill_str, bill_id in not_payed_bills %}
                    <li><a href="{% url 'bills:bill' bill_id=bill_id %}">{{ bill_str }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="actionsBox">
        <l1 class="title">Add Bill</l1>
        <form action="{% url 'bills:add' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Bill name</label>
                <input class="form-control" type="text" placeholder="name e.g. Лавка" name="name">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Date of the bill</label>
                <input class="form-control" type="date" placeholder="date" name="date">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Choose who payed</label>
                <select class="form-control" name="lender">
                    {% for user in users %}
                    <option value="{{ user.id }}">{{ user }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Comment</label>
                <input class="form-control" type="text" placeholder="comment" name="comment">
                <small class="form-text text-muted">Comment is optional </small>
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
    <div class="actionsBox">
        <l1 class="title">Delete Bill</l1>
        <form action="{% url 'bills:delete_bill' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Choose bill</label>
                <select class="form-control" name="bill_id">
                    {% for bill_str, bill_id in not_payed_bills %}
                    <option value="{{ bill_id }}">{{ bill_str }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

bills/templates/bills/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/bill.css' %}">
    <title>Bills</title>
</head>

<body>
    <div id="page-container">
        <header>
            <div class="header-menu">
                <div class="header-menu-item">
                    <a href="{% url 'users:index' %}">
                        Home
                    </a>
                </div>
                <div class="header-menu-item-current">
                    <a href= "{% url 'bills:index' %}">
                        Bills
                    </a>
                </div>
            </div>
            <div class="header-right-menu">
                <div class="header-right-menu-add-bill-box">+$</div>
                <div class="header-right-menu-user-box">
                    {{ first_name_first_letter }}{{ last_name_first_letter }}
                </div>
            </div>
        </header>
        <div class="account-popup-window" style="display:none;">
            <div class="account-popup-window-textbox">
                <h5 class="bold">{{ user.first_name }} {{ user.last_name }}</h5>
                <h6>{{ user.email }}</h6>
            </div>
            <a href="{% url 'users:logout' %}" style="text-decoration: none;">
                <div class="account-popup-window-signountbox">
                    <h6>Sign out</h6>
                </div>
            </a>
        </div>
        <div id="content-wrap">
            {% block body %}
            {% endblock %}
        </div>
        <footer id="footer">
            Если сайт не работает, звоните Владимиру: +7 985 455-24-65
        </footer>
    </div>
    <script src="{% static '/js/bill.js' %}"></script>
</body>

</html>

bills/templates/bills/layoutOld.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
        <title>Bills</title>
    </head>
    <body>
        <header>
            <nav>
                <ul class="menu">
                    <li class="menu-item"><a href= {% url 'users:index' %}>Main</a></li>
                    <li class="menu-item-current"><a href= {% url 'bills:index' %}>Bills</a></li>
                    <li class="menu-item">API</li>
                    <li class="menu-item">About</li>
                </ul>
            </nav>
        </header>
        {% block body %}
        {% endblock %}
    </body>
</html>