Accounting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('users/', include('users.urls')),
    path('bills/', include('bills.urls')),
    path('api/', include('api.urls'))
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getData, name='getData'),
]

bills/urls.py
from django.urls import path
from . import views

app_name = 'bills'
urlpatterns = [
    path('', views.index, name='index'), #, namespace='bills'
    path('add', views.add, name='add'),
    path('delete_bill', views.delete_bill, name='delete_bill'),
    path('<int:bill_id>', views.bill, name='bill'),
    path('<int:bill_id>/add_item', views.add_item, name='add_item'),
    path('<int:bill_id>/assign_payment', views.assign_payment, name='assign_payment'),
    path('<int:bill_id>/delete_payment', views.delete_payment, name='delete_payment'),
    path('api/get_bills', views.get_bills, name='api_get_bills'),
    path('api/get_all_users', views.get_all_users, name='get_all_users')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('pay/<str:lender_username>', views.pay, name='pay'),
    path('pay/<str:lender_username>/make_payment', views.make_payment, name='make_payment'),
    path('receive/<str:borrower_username>', views.receive, name='receive'),
    path('receive/<str:borrower_username>/receive_payment', views.receive_payment, name='receive_payment')
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, get_user_model
from bills.models import Bill, Item, Item_Payment

## custom libs
import python_libs.send_email as se

# Create your views here.
# clean terminal print("\033[H\033[J", end="")
def index(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))

    ### declare main function ###
    acc_user = request.user

    # counting Account payable total and grouped by lender username
    account_payable = 0
    account_payable_by_lender = {}
    for user in get_user_model().objects.exclude(id = acc_user.id).all():
        account_payable_by_lender[user.first_name] = 0

    for payment in Item_Payment.objects.filter(payer = acc_user).filter(is_payed = False).all():
        account_payable -= payment.paying_amount
        lender_id = payment.item.bill.lender.id
        lender_first_name = get_user_model().objects.get(id = lender_id).first_name
        account_payable_by_lender[lender_first_name] -= payment.paying_amount
    

    # counting Account receivable total and grouped by borrower username
    account_receivable = 0
    account_receivable_by_borrower = {}
    for user in get_user_model().objects.exclude(id = acc_user.id).all():
        account_receivable_by_borrower[user.first_name] = 0

    for payment in Item_Payment.objects.all():
        if payment.lender == acc_user and payment.is_payed == False:
            account_receivable += payment.paying_amount
            account_receivable_by_borrower[payment.payer.first_name] += payment.paying_amount


    # counting Net result = account_receivable + account_payable
    # because accounts payable are negative
    account_Net = account_receivable + account_payable
    account_Net_by_user = account_receivable_by_borrower.copy()

    for key in account_payable_by_lender:
        account_Net_by_user[key] += account_payable_by_lender[key]

    
    # rounding results
    account_payable = round(account_payable)
    account_receivable = round(account_receivable)
    account_Net = round(account_Net)

    for key in account_payable_by_lender:
        account_payable_by_lender[key] = round(account_payable_by_lender[key])

    for key in account_receivable_by_borrower:
        account_receivable_by_borrower[key] = round(account_receivable_by_borrower[key])

    for key in account_Net_by_user:
        account_Net_by_user[key] = round(account_Net_by_user[key])

    ##################### main script #####################
    ########################################################

    if request.method != 'POST':
        return render(request, 'users/account.html', {
                'user': acc_user,
                'first_name_first_letter': acc_user.first_name[0],
                'last_name_first_letter': acc_user.last_name[0],
                'account_payable': account_payable,
                'account_payable_by_lender': account_payable_by_lender,
                'account_receivable': account_receivable,
                'account_receivable_by_borrower': account_receivable_by_borrower,
                'account_Net': account_Net,
                'account_Net_by_user': account_Net_by_user,
            })

    elif request.method == 'POST':
        contr_agent_first_name = request.POST['contr_agent_first_name']
        contr_agent = get_user_model().objects.get(first_name = contr_agent_first_name)
        contr_agent_fn = contr_agent.first_name
        payment_type = request.POST['payment_type']
        acc_user = request.user
        acc_user_fn = acc_user.first_name

        if payment_type == 'payable':
            #closing payables
            amount = 0
            for payment in Item_Payment.objects.filter(payer = acc_user).filter(is_payed = False).all():
                if payment.item.bill.lender.id == contr_agent.id:
                    amount += payment.paying_amount
                    Item_Payment.objects.filter(id = payment.id).update(is_payed = True)

            #sending emails payables
            se.send_payment_email(contr_agent.email, contr_agent_fn, acc_user_fn, amount)
            se.get_payment_email(acc_user.email, contr_agent_fn, acc_user_fn, amount)

            return HttpResponseRedirect(reverse('users:index'))
            
        
        elif payment_type == 'receivable':
            #closing receivables
            amount = 0
            for payment in Item_Payment.objects.all():
                if payment.lender == acc_user and payment.is_payed == False:
                    amount += payment.paying_amount
                    Item_Payment.objects.filter(id = payment.id).update(is_payed = True)


            #sending emails receivables
            se.get_payment_email(contr_agent.email, acc_user_fn, contr_agent_fn, amount)
            se.send_payment_email(acc_user.email, acc_user_fn, contr_agent_fn, amount)

            return HttpResponseRedirect(reverse('users:index'))
        
        elif payment_type == 'net':
            #closing payables
            amount = 0
            for payment in Item_Payment.objects.filter(payer = acc_user).filter(is_payed = False).all():
                if payment.item.bill.lender.id == contr_agent.id:
                    amount -= payment.paying_amount
                    Item_Payment.objects.filter(id = payment.id).update(is_payed = True)

            #closing receivables
            for payment in Item_Payment.objects.all():
                if payment.lender == acc_user and payment.is_payed == False:
                    amount += payment.paying_amount
                    Item_Payment.objects.filter(id = payment.id).update(is_payed = True)
            
            if amount < 0:
                #sending emails payables
                amount = abs(amount)
                se.send_payment_email(contr_agent.email, contr_agent_fn, acc_user_fn, amount)
                se.get_payment_email(acc_user.email, contr_agent_fn, acc_user_fn, amount)
            else:
                #sending emails receivables
                se.get_payment_email(contr_agent.email, acc_user_fn, contr_agent_fn, amount)
                se.send_payment_email(acc_user.email, acc_user_fn, contr_agent_fn, amount)
                
            return HttpResponseRedirect(reverse('users:index'))







def login_view(request):
    if request.method == 'POST' and len(request.POST['password']) == 0:
            emails = get_user_model().objects.values_list('email', flat=True).all()
            email = request.POST['email']
            if email in emails:
                user = get_user_model().objects.get(email = email)
                first_name = user.first_name
                last_name = user.last_name
                return render(request, 'users/login.html', {
                    'first_name': first_name,
                    'first_name_first_letter': first_name[0],
                    'last_name': last_name,
                    'last_name_first_letter': last_name[0],
                    'email': email,
                    'form_numer': 2,
                })
            else:
                return render(request, 'users/login.html', {
                    'form_numer': 1,
                    'message': 'incorrect email'
                })
    elif request.method == 'POST' and len(request.POST['password']) > 0:
        email = request.POST['email']
        password = request.POST['password']
        username = get_user_model().objects.get(email = email).username
        first_name =  get_user_model().objects.get(email = email).first_name
        last_name =  get_user_model().objects.get(email = email).last_name
        user = authenticate(request, username = username, password = password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))

        else:
            return render(request, 'users/login.html', {
            'first_name': first_name,
            'first_name_first_letter': first_name[0],
            'last_name': last_name,
            'last_name_first_letter': last_name[0],
            'email': email,
            'form_numer': 2,
            'message': f'Email or Password is incorrect'
            })


    return render(request, 'users/login.html', {
        'form_numer': 1
    })



def logout_view(request):
    logout(request)
    return render(request, 'users/login.html')



def pay(request, lender_username):
    # form with multiple https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
    user = request.user
    lender = get_user_model().objects.get(username = lender_username)
    
    # making lst for [bill_name,  bill_total_sum, [payment_id, payment_name, paying_amount, paying_part]]
    bill_payment = []
    for bill in Bill.objects.filter(lender = lender).all():
        payments_lst = []
        bill_total = 0
        for item in Item.objects.filter(bill = bill).all():
            for payment in Item_Payment.objects.filter(item = item).filter(payer = user).filter(is_payed = False).all():
                payments_lst.append([payment.id, payment.item.name, payment.paying_amount, payment.paying_part])
                bill_total += payment.paying_amount
        if not (payments_lst == []):
            bill_payment.append([str(bill), bill_total, payments_lst])

    return render(request, 'users/pay.html', {
        'user': user,
        'lender': lender,
        'bill_payment': bill_payment
    })


def make_payment(request, lender_username):
    if request.method == 'POST':
        payment_id = int(request.POST['payment_id'])
        Item_Payment.objects.filter(id = payment_id).update(is_payed=True)
        return HttpResponseRedirect(reverse('users:pay', args=(lender_username, )))


def receive(request, borrower_username):
    user = request.user

users/templates/users/account.html
{% extends 'users/layout.html' %}

{% block body %}

<h1>Account</h1>
<div class="account-menu">
    <div class="account-menu-items" id="account-menu-item-net">Net</div>
    <div class="account-menu-items" id="account-menu-item-payable">Payable</div>
    <div class="account-menu-items" id="account-menu-item-receivable">Receivable</div>
</div>

<table class="account-table" id="account-table-net">
    {% if account_Net_by_user %}
    {% for key, value in account_Net_by_user.items %}
    <tr>
        <td class="user">{{ key }}</td>
        <td class="amount">{{ value }}</td>
        <td class="rub">rub</td>
        <td>
            <form action="{% url 'users:index' %}" method="post">
                {% csrf_token %}
                <input name="contr_agent_first_name" value="{{ key }}" style="display:none" class="hidden-input">
                <input name="payment_type" value="net" style="display:none" class="hidden-input">
                <button type="submit">Pay</button>
            </form>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td class="user total">Total</td>
        <td class="amount total">{{ account_Net }}</td>
        <td class="rub total">rub</td>
        <td></td>
    </tr>
    {% endif %}
</table>



<table class="account-table" style="display:none;" id="account-table-payable">
    {% if account_payable_by_lender %}
    {% for key, value in account_payable_by_lender.items %}
    <tr>
        <td class="user">{{ key }}</td>
        <td class="amount">{{ value }}</td>
        <td class="rub">rub</td>
        <td>
            <form action="{% url 'users:index' %}" method="post">
                {% csrf_token %}
                <input name="contr_agent_first_name" value="{{ key }}" style="display:none" class="hidden-input">
                <input name="payment_type" value="payable" style="display:none" class="hidden-input">
                <button type="submit">Pay</button>
            </form>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td class="user total">Total</td>
        <td class="amount total">{{ account_payable }}</td>
        <td class="rub total">rub</td>
        <td></td>
    </tr>
    {% endif %}
</table>

<table class="account-table" style="display:none;" id="account-table-receivable">
    {% if account_receivable_by_borrower %}
    {% for key, value in account_receivable_by_borrower.items %}
    <tr>
        <td class="user">{{ key }}</td>
        <td class="amount">{{ value }}</td>
        <td class="rub">rub</td>
        <td>
            <form action="{% url 'users:index' %}" method="post">
                {% csrf_token %}
                <input name="contr_agent_first_name" value="{{ key }}" style="display:none" class="hidden-input">
                <input name="payment_type" value="receivable" style="display:none" class="hidden-input">
                <button type="submit">Receive</button>
            </form>
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td class="user total">Total</td>
        <td class="amount total">{{ account_receivable }}</td>
        <td class="rub total">rub</td>
        <td></td>
    </tr>
    {% endif %}
</table>
{% endblock %}

users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/account.css' %}">
    <title>Users</title>
</head>

<body>
    <div id="page-container">
        <header>
            <div class="header-menu">
                <div class="header-menu-item-current">
                    <a href="{% url 'users:index' %}">
                        Home
                    </a>
                </div>
                <div class="header-menu-item">
                    <a href= "{% url 'bills:index' %}">
                        Bills
                    </a>
                </div>
            </div>
            <div class="header-right-menu">
                <div class="header-right-menu-add-bill-box">+$</div>
                <div class="header-right-menu-user-box">
                    {{ first_name_first_letter }}{{ last_name_first_letter }}
                </div>
            </div>
        </header>
        <div class="account-popup-window" style="display:none;">
            <div class="account-popup-window-textbox">
                <h5 class="bold">{{ user.first_name }} {{ user.last_name }}</h5>
                <h6>{{ user.email }}</h6>
            </div>
            <a href="{% url 'users:logout' %}" style="text-decoration: none;">
                <div class="account-popup-window-signountbox">
                    <h6>Sign out</h6>
                </div>
            </a>
        </div>
        <div id="content-wrap">
            {% block body %}
            {% endblock %}
        </div>
        <footer id="footer">
            Если сайт не работает, звоните Владимиру: +7 985 455-24-65
        </footer>
    </div>
    <script src="{% static '/js/account.js' %}"></script>
</body>

</html>

users/templates/users/layoutLogin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    <title>Users</title>
</head>

<body>
    <div id="page-container">
        <div id="content-wrap">
            {% block body %}
            {% endblock %}
        </div>
        <footer id="footer">
            Если сайт не работает, звоните Владимиру: +7 985 455-24-65
        </footer>
    </div>
    {% if form_numer %}
        <div class="toshow" style="display:none" id="form_numer">{{ form_numer }}</div>
    {% endif %}
    <script src="{% static '/js/login.js' %}"></script>
</body>

</html>

users/templates/users/login.html
{% extends 'users/layoutLogin.html' %}

{% block body %}
<div class="form" id="form">
    <h1>Sign in</h1>
    <h2>Continue with email</h2>
    <h3 style="font-weight: normal;">New user? 
        <a href="{% url 'users:logout' %}" class="link" style="text-decoration: none;">
            Create an account
        </a>
    </h3>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="password" name="password" value="" style="display:none;">
        <div class="input-box">
            <h5 class="input-hint">Email address</h5>
            <input type="text" name="email" id="email">
        </div>
        {% if message %}
        <h5>{{message}}</h5>
        {% endif %}
        <button class="btn-login" type="submit">Continue</button>
    </form>
</div>



<div class="form" id="form" style="display:none;">
    <h1>Enter your password</h1>
    <div class="login-user-box">
        <div class="login-user-box-circle">
            {{ first_name_first_letter }}{{ last_name_first_letter }}
        </div>
        <div class="login-user-box-info">
            <h5>{{ first_name }} {{ last_name }}</h5>
            <h5>{{ email }}</h5>
        </div>
    </div>

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <!-- hidden email input -->
        <input type="text" name="email" value="{{ email }}" style="display:none;">
        <div class="input-box">
            <h4 class="input-hint">Password</h4>
            <div class="input">
                <input type="password" name="password" id="password">
                <div class="bi bi-eye-slash" id="see-password-icon"></div>
            </div>
        </div>
        {% if message %}
        <h5>{{message}}</h5>
        {% endif %}
        <button class="btn-login" type="submit">Continue</button>
    </form>
</div>
{% endblock %}

users/templates/users/loginLayout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <title>Users</title>
</head>

<body>
    <div id="page-container">
        <div id="content-wrap">
            {% block body %}
            {% endblock %}
        </div>
        <footer id="footer">
            Если сайт не работает, звоните Владимиру: +7 985 455-24-65
        </footer>
    </div>
    {% if form_numer %}
        <div class="toshow" style="display:none" id="form_numer">{{ form_numer }}</div>
    {% endif %}
    <script src="{% static '/js/login.js' %}"></script>
</body>

</html>

users/templates/users/pay.html
{% extends 'users/layout.html' %}

{% block body %}
<header class="subHeader">
    <div>
        {% if user.first_name %}
        <l1 class="title">{{ user.first_name }} pays to {{ lender }}</l1>
        {% else %}
        <l1 class="title">{{ user.username }} pays to {{ lender }}</l1>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </div>
</header>

<div class="mainBox">
    {% if bill_payment %}
    <div>
        {% for bill, bill_total, payment in bill_payment %}
        <div class="subMainBox">
            <div style="width: 50%;">
                <l1 class="title">{{bill}}</l1>
                <div class="card">
                    <div class="card-body">
                        <ul class="list">
                            {% for payment_id, item_name, paying_amount, paying_part in payment %}
                            <li>For {{item_name}} pay {{paying_amount}} ({{paying_part}} share)</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="paymentsBox" style="padding-left: 10%; padding-top: 5%;">
                <form action="{% url 'users:make_payment' lender.username %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Choose payment</label>
                        <select name="payment_id" class="form-control">
                            {% for payment_id, item_name, paying_amount, paying_part in payment %}
                            <option value="{{ payment_id }}">For {{item_name}} pay {{paying_amount}} ({{paying_part}}
                                share)</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Make payment</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div>
        <l1>You have no payments</l1>
    </div>
    {% endif %}
</div>
{% endblock %}

users/templates/users/receive.html
{% extends 'users/layout.html' %}

{% block body %}

<header class="subHeader">
    <div>
        {% if user.first_name %}
        <l1 class="title">{{ user.first_name }} receive from {{ borrower }}</l1>
        {% else %}
        <l1 class="title">{{ user.username }} receive from {{ borrower }}</l1>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'users:logout' %}">Log Out</a>
    </div>
</header>

<div class="mainBox">
    {% if bill_payment %}
    <div>
        {% for bill, bill_total, payment in bill_payment %}
        <div class="subMainBox">
            <div style="width: 50%;">
                <l1 class="title">{{bill}}</l1>
                <div class="card">
                    <div class="card-body">
                        <ul class="list">
                            {% for payment_id, item_name, paying_amount, paying_part in payment %}
                            <li>For {{item_name}} pay {{paying_amount}} ({{paying_part}} share)</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="paymentsBox" style="padding-left: 10%; padding-top: 5%;">
                <form action="{% url 'users:receive_payment' borrower.username %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Choose payment</label>
                        <select name="payment_id" class="form-control">
                            {% for payment_id, item_name, paying_amount, paying_part in payment %}
                            <option value="{{ payment_id }}">For {{item_name}} pay {{paying_amount}} ({{paying_part}}
                                share)</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Make payment</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div>
        <l1>You have no payments</l1>
    </div>
    {% endif %}
</div>
{% endblock %}